### ISSUE TITLE
System not configured for boot environments

### ISSUE THREAD

**Issue by seonwoolee** [Finic8/zbectl#1]
No matter what command I run, including `zbectl install /dev/sda` (I use GRUB and BIOS booting), I get the error message
`ERROR: This system is not configured for boot environments`

**Comment by Finic8** [comment]
Can you provide some information about your setup especially your pool layout and from what context you are running `zbectl`?
This error is supposed to mean your datasets are not configured appropriately.
`zfs list` should return something like this:
```
NAME                        MOUNTPOINT
yourpool/ROOT/default        /
```

**Comment by seonwoolee** [comment]
I'm feeling a little lost because the documentation seems a little lacking.

I'm running Arch Linux. I installed your package through the AUR. After installing the package, I tried `zbectl install /dev/sda` and got the error above.

I have Arch Linux installed on ZFS. `zfs list` returns 
```
NAME         USED  AVAIL  REFER  MOUNTPOINT
zroot       42.7G  24.0G    96K  none
zroot/home  6.43G  24.0G   996M  legacy
zroot/root  36.1G  24.0G  12.4G  /
```

**Comment by Finic8** [comment]
Okay I can see that the documentation is not sufficient and I will definitely add a proper installation guide to avoid this issue in the future.
So the way you have to do it is like this:
```
NAME                   USED  AVAIL  REFER  MOUNTPOINT
zroot                   251G   206G    96K  /zroot
zroot/ROOT              105G   206G   128K  /zroot/ROOT
zroot/ROOT/default     30.4G   206G  18.8G  /
zroot/ROOT/base        2.73G   206G  3.45G  /
```
In this example `base` and `default` are two boot environments.
All your environments have to be located under `yourpoolname/ROOT` in your case `zroot/ROOT`.
So you have to create a dataset `zroot/ROOT` and `zroot/ROOT/default` and move your installation to the latter one.
This means `default` will be the name of your boot environment, although that is entirely up to you.
Afterwards you can run `zbectl install /dev/sda` and the error should be resolved.

I would also recommend setting the mountpoint of your home dataset using `zfs set mountpoint=/home zroot/home` instead of using legacy mounting, but that's just some friendly advice.
